### ISSUE TITLE
Long text options

### ISSUE THREAD

**Issue by martiendt** [TerryZ/v-selectmenu#13]
Hi, if i have an option with long text, it will offset from browser. This need ability to wrap the text into multiple row.

![screen shot 2018-10-24 at 9 11 23 am](https://user-images.githubusercontent.com/2176011/47401781-e0a2b700-d76c-11e8-9a90-db1e76f99ff6.png)

**Comment by martiendt** [comment]
```
.sm-item-text {
  white-space: pre-wrap;
}
````
I tried added this but i got other issue with v-dropdown dependencies, it should prevent `left: <minus>`

![screen shot 2018-10-24 at 10 43 39 am](https://user-images.githubusercontent.com/2176011/47404996-befbfc80-d779-11e8-8140-d70545746559.png)

**Comment by TerryZ** [comment]
Fixed in version `v2.0.2`.
