### ISSUE TITLE
Button text is not being updated 

### ISSUE THREAD

**Issue by anshumansworld** [TerryZ/v-selectmenu#16]
After selecting an option button text should be changed. It always shows `Select an option`

```
<v-selectmenu v-model="state.selectedChatFilter"
                          :regular="true"
                          :data="chatFilters"></v-selectmenu>
```

```
chatFilters: [
	{name: 'Active Chats', id: 'activeChats', content: 'Active Chats'},
	{name: 'Closed Chats', id: 'closedChats', content: 'Closed Chats'},
	{name: 'All Chats', id: 'allChats', content: 'All Chats'}
]
selectedChatFilter = 'activeChats'
```

Also if I remove key `content` from list, text (`Active Chats`/`Closed Chats`/`All Chats`) is not being displayed in options

**Comment by TerryZ** [comment]
Please try upload your code to codepen, jsfiddle or jsbin.

**Comment by anshumansworld** [comment]
Here is the stackblitz url: https://stackblitz.com/edit/vue-czssb2

**Comment by TerryZ** [comment]
No way to close header in advanced mode so far. In future release can set `:title="false"` to close.
