### ISSUE TITLE
Select Menu doesn't seem to update if data modifies

### ISSUE THREAD

**Issue by rlightner** [TerryZ/v-selectmenu#17]
I'm lazying loading the contents and the drop down doesn't seem to rebind the data source.

**Comment by TerryZ** [comment]
Can you post your code or upload to somewhere like `jsFiddle`, `CodePen`

**Comment by radarsu** [comment]
Got same error. Tried using computed properties and several workarounds, but it still didn't work.

**Comment by TerryZ** [comment]
Fixed in latest version.
