### ISSUE TITLE
Setting regular to true doesn't respect key-field or show-field

### ISSUE THREAD

**Issue by rlightner** [TerryZ/v-selectmenu#18]

**Comment by TerryZ** [comment]
![image](https://user-images.githubusercontent.com/854406/50411285-cc953780-0839-11e9-9c64-c11873ccefff.png)


Please checkout the code in [v-selectmenu offical site](https://terryz.github.io/vue/#/selectmenu/demo), the regular menu is using fixed data format:

```js
[
	{content:'163 NetEase',url : 'http://www.163.com'},
	{content:'Sina',disabled: true, url : 'http://www.sina.com'},
	{content:'sm_divider'},
	{content:'<i class="fa fa-fw fa-github"></i> GitHub',url : 'https://github.com'},
	{content:'callback',callback : function(){ alert('clicked!'); },
	{...}
]
```

**Comment by TerryZ** [comment]
`show-field`, `key-field` option only work on advanced mode.

**Comment by rlightner** [comment]
Can I ask why it couldn't support show-field and key-field? Something you would accept a pull request on?

**Comment by TerryZ** [comment]
Because regular mode have different rendering way with advanced mode.

**Comment by asalgan** [comment]
@TerryZ I'm trying to use the show-field on an advanced menu and it isn't working. When I select an option it doesn't show up in the menu as the selected option, it remains blank, any ideas as to why?
