### ISSUE TITLE
use router-links in NESTED menu?

### ISSUE THREAD

**Issue by riddley** [TerryZ/v-selectmenu#33]
You sent me this on reddit:
```
For custom router-link:

<v-selectmenu :data="list" type="regular" >
  <template #row="{ row }">
    <router-link :to="row.url" >{{row.name}}</router-link>
  </template>
</v-selectmenu>
```

But that doesn't seem to work if the menu is nested. Is it possible to use router-links for nested items?

**Comment by TerryZ** [comment]
What version of `vuejs` are you using? `v-selectmenu` required `2.6.0+`, please check on this.

**Comment by riddley** [comment]
I'm not able to install version 2.6.0. Has it been released?

**Comment by TerryZ** [comment]
The vuejs [last release](https://github.com/vuejs/vue/releases) is [2.6.11](https://github.com/vuejs/vue/releases/tag/v2.6.11)

**Comment by riddley** [comment]
Oh Sorry, I read that as the version for v-selectmenu. I am using Vue 2.6.11.

**Comment by TerryZ** [comment]
Try upload your code to somewhere, then i can see what happen.

**Comment by riddley** [comment]
https://codepen.io/riddley/pen/BaygyBE

**Comment by TerryZ** [comment]
First of all, your demo does not work, because miss a comma in line 117.

![image](https://user-images.githubusercontent.com/854406/73590456-853da800-451d-11ea-96b5-bbea1f78e5e4.png)

And i don't see any `router-link` in your demo.

**Comment by riddley** [comment]
I was able to get this working. Thanks for your help!
