### ISSUE TITLE
Customize Header

### ISSUE THREAD

**Issue by dionfananie** [TerryZ/v-selectmenu#4]
could i change your header v-selectmenu "select an option" ?, i wanna make some customization in header. please can you make it customizeable?

**Comment by TerryZ** [comment]
Please check `title` option on official website [demo page](https://terryz.github.io/vue/#/selectmenu/demo).

**Comment by radarsu** [comment]
Title changes header after opening a dropdown. But is there an option to change "Select an option" text or apply custom translations?

**Comment by themaxaboy** [comment]
> Title changes header after opening a dropdown. But is there an option to change "Select an option" text or apply custom translations? Could you reopen?

mounted() {
    this.$refs.sm.i18n.advance_default = "Please select an option...";
    this.$refs.sm.i18n.not_found = "Not Found.";
}

**Comment by TerryZ** [comment]
> > Title changes header after opening a dropdown. But is there an option to change "Select an option" text or apply custom translations? Could you reopen?
> 
> ```js
> mounted() {
>     this.$refs.sm.i18n.advance_default = "Please select an option...";
>     this.$refs.sm.i18n.not_found = "Not Found.";
> }
> ```

Good job!
