### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by xeroxstar** [TerryZ/v-selectmenu#8]
Great UI and i gave u a star and forked this UI but where is the documentation?  Simple things should be explained better, for example, how do i change "select an option" ? I don't want use i18n but i have too, and i can't change the title without language.js. I need a dynamic option to change the title but i couldn't find anything on GH (i am sure there is a way to do it). I don't want to use Vue.use(), how do i use it without "use()"? How can i use the {options} without use()?  These small things should have examples or documentation. As i said, great UI(loved it), but not many will use it only because we don't have examples or documentation and running through the code to understand how it works some dev have no time. The documentation or good examples solve these problems. What i found is a short briefing and this is not enough to make the development enjoyable.

**Comment by xeroxstar** [comment]
Thx but i ended up to use custom button inside the select like this:

`<v-selectmenu><div class='btn'/></v-selectmenu>`

Like this, i have more control over the button 🥇 I will keep playing with it, nice UI 👍

**Comment by xeroxstar** [comment]
I run in another issue, how to i make one of the options been selected by default? I guess i have to put "selected" in the menu array like this
```
menu: [
                {
                  title: 'Limits',
                  list: [
                    {content:'+100 -500'},
                    {content:'+500 -1000',selected:true},
                    {content:'+1000 -2000'},
                  ]
                }
              ]
```
But it wont make the option selected on load, any suggestions?

**Comment by TerryZ** [comment]
The regular menu can not be selected, mey be you can try advance menu mode.

**Comment by xeroxstar** [comment]
I am not sure what is "advance menu mode"? I have this code(is it advanced or no i am not sure):

```
<v-selectmenu
      :data="menu">
      <div class="select-btn"> <font-awesome-icon icon="filter" style="margin-right: 10px"/> Filter settings 
    </div>
</v-selectmenu>

export default {
  name: 'App',
  data:function(){
  
    return{    
      menu: [
        {
          title: 'Limits',
          list: [
            {index:0,content:'+100 -500'},
            {index:1,content:'+500 -1000',selected:'selected'},
            {index:2,content:'+1000 -2000'},
          ]
        }
      ]
    }
  }
}
```

**Comment by xeroxstar** [comment]
this example i found only [here](https://terryz.github.io/vue/#/selectmenu/demo) an example for selected menus but it's do not show how you select them by default.

**Comment by xeroxstar** [comment]
Never mind, i found the solution, i have to set the value on v-model="value"

`return { value:1}`

to select the option on default

**Comment by TerryZ** [comment]
Yeah, set 'v-model' to set default selected item
